version: "3"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    network_mode: service:graphite

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - grafana-net

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    ports:
      - "8080:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    networks:
      - grafana-net

networks:
  grafana-net: